FROM balenalib/%%BALENA_MACHINE_NAME%%-node:16-bullseye-run

RUN install_packages vlc dbus-x11
#vlc-plugin-*

COPY . /code/
WORKDIR /code/

RUN sed -i -e 's/\r$//' scripts/start.sh
CMD ["bash","scripts/start.sh"]