version: "2"
volumes:
  vlc:
  xserver:
services:
  vlc:
    build: ./balena-vlc
    devices:
      - /dev/dri # needs exteral xserver running https://github.com/wirewirewirewire/xserver
    group_add:
      - video # needs exteral xserver running https://github.com/wirewirewirewire/xserver
    volumes:
      - "vlc:/code/drive" # Only required if using PERSISTENT flag (see below)
      - "xserver:/tmp/.X11-unix" # needs exteral xserver running https://github.com/wirewirewirewire/xserver
    labels:
      io.resin.features.dbus: "1"
      io.resin.features.kernel-modules: "1"
      io.resin.features.firmware: "1"
      io.balena.features.supervisor-api: "1"
